### ISSUE TITLE
MTA logo

### ISSUE THREAD

**Issue by redaiq90** [pkfln/mta-discord-rpc#19]
The mta logo in discord not shown in windows 7
![ds](https://user-images.githubusercontent.com/60717660/156510191-416852cd-b215-455b-929f-d30c394a0d21.PNG)

**Comment by pkfln** [comment]
Please read the troubleshooting guide. Specifically this: https://github.com/pkfln/mta-discord-rpc#discord-shows-mta-san-andreas-as-my-current-game

**Comment by redaiq90** [comment]
I did it but the status won't show in discord but when I come to add in
manually it's available MTA : San Andreas

في الجمعة، ٢٥ مارس ٢٠٢٢ ١٠:٥٦ م pkfln ***@***.***> كتب:
