### ISSUE TITLE
error: could not find mta installation path. (1)

### ISSUE THREAD

**Issue by 15hk** [pkfln/mta-discord-rpc#20]
**hello
when i start the mta-discord-rpc.exe
he told me 
error: could not find mta installation path. (1)
can you help me to fix this**

**Comment by pkfln** [comment]
What OS are you using? And did you install MTA properly, if so, which MTA version are you running?

**Comment by 15hk** [comment]
**windows 11 . yah mta last version
i fixed the error
i reinstall mta and gta
and now it's working well 
thank you for reading**

**Comment by pkfln** [comment]
Great, thanks for sharing your fix.
