### ISSUE TITLE
Error:could not find mta installation path. (2)

### ISSUE THREAD

**Issue by r0401** [pkfln/mta-discord-rpc#3]
this is my first time using github i dunno if this is the right place to get help but i get this error when ever i try to start this i get this error i tried to put in mta root  tried run as admin  doesnt work

**Comment by pkfln** [comment]
You probably reinstalled MTA into a different path. Check the default value of **HKEY_LOCAL_MACHINE\SOFTWARE\Classes\mtasa\shell\open\command** in your Windows Registry and adjust the value between the quotes to the new path of your MTA installation:
![image](https://user-images.githubusercontent.com/14312017/106401965-71c26700-6427-11eb-94a8-453e5c50983f.png)

**Comment by r0401** [comment]
fixed now i click close issue right?

**Comment by pkfln** [comment]
I closed it for you. :)
